<?php
/** @var \Commerce365\Quotes\Block\QuoteDetails  $block */
$order = $block->getQuote();
$orderLines = $block->safeGet($order, 'Lines', []);
?>

<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"><?= __('Quote #') ?><?= $block->safeGet($order, 'No.'); ?> </span>
    </h1>
    <span class="order-status"><?= $block->getQuoteStatus($order) ?></span>
    <div class="order-date">
        <span class="label"><?= __('Quote Date:') ?></span> <date><?= date_format(date_create($block->safeGet($order, 'Document Date')),"d-m-Y") ?></date>
    </div>
</div>

<div class="actions-toolbar order-actions-toolbar">
    <div class="actions">
        <a href="<?= $block->safeGet($order, 'PDFUrl') ?>" class="action order" target="_blank">
            <span><?= __('Download PDF') ?></span>
        </a>
    </div>
</div>

<ul class="items order-links"><li class="nav item current"><strong><?= __('Items Quoted') ?></strong></li></ul><div class="order-details-items ordered">

    <div class="order-title">
        <strong><?= __('Items Quoted') ?></strong>
    </div>

    <div class="table-wrapper order-items">
        <table class="data table table-order-items" id="my-orders-table">
            <caption class="table-caption"><?= __('Items Quoted') ?></caption>
            <thead>
            <tr>
                <th class="col name"><?= __('Product Name') ?></th>
                <th class="col sku"><?= __('SKU') ?></th>
                <th class="col price"><?= __('Price') ?></th>
                <th class="col qty"><?= __('Qty') ?></th>
                <th class="col subtotal"><?= __('Subtotal') ?></th>
            </tr>
            </thead>

            <?php
            foreach ($orderLines as $orderLine) {
                $itemNo = ((int)$block->safeGet($orderLine, 'Type') === 2) ? $block->safeGet($orderLine, 'No.') : '';
                if ($block->safeGet($orderLine, 'Type') < 1)
                    echo '<tbody>
                        <tr id="order-item-row-1">
                            <td class="col name" data-th="Product Name">
                                <strong class="product name product-item-name">' . $block->safeGet($orderLine, 'Description') . '</strong>
                            </td>
                            <td class="col sku" data-th="SKU"></td>
                            <td class="col price" data-th="Price">
                            </td>
                            <td class="col qty" data-th="Qty">
                            </td>
                            <td class="col subtotal" data-th="Subtotal">
                            </td>
                        </tr>
                    </tbody>';
                else {
                    $qty = max((float)$block->safeGet($orderLine, 'Quantity'), 1);
                    echo '<tbody>
                            <tr id="order-item-row-1">
                                <td class="col name" data-th="Product Name">
                                    <strong class="product name product-item-name">' . $block->safeGet($orderLine, 'Description') . '</strong>
                                </td>
                                <td class="col sku" data-th="SKU">' . $itemNo . '</td>
                                <td class="col price" data-th="Price">
                                    <span class="price-excluding-tax" data-label="Excl. Tax">
                                        <span class="cart-price">
                                            <span class="price">' . $block->safeGet($orderLine, 'Currency Code') . ' ' . number_format((float)$block->safeGet($orderLine, 'Amount') / $qty, 2, ',', '.') . '</span>
                                        </span>
                                    </span>
                                </td>
                                <td class="col qty" data-th="Qty">
                                    <ul class="items-qty">
                                        <li class="item">
                                            <span class="content">' . $block->safeGet($orderLine, 'Quantity') . '</span>
                                        </li>
                                    </ul>
                                </td>
                                <td class="col subtotal" data-th="Subtotal">
                                    <span class="price-excluding-tax" data-label="Excl. Tax">
                                        <span class="cart-price">
                                            <span class="price">' . $block->safeGet($orderLine, 'Currency Code') . ' ' . number_format((float)$block->safeGet($orderLine, 'Line Amount'), 2, ',', '.') . '</span>
                                        </span>
                                    </span>
                                </td>
                            </tr>
                        </tbody>';
                }
            }
            ?>

            <tfoot>
            <tr class="subtotal">
                <th colspan="4" class="mark" scope="row">
                    <?= __('Subtotal') ?>
                </th>
                <td class="amount" data-th="Subtotal">
                    <span class="price"><?= $block->safeGet($order, 'Currency Code') ?> <?= number_format((float)$block->safeGet($order, 'Amount'), 2, ',', '.') ?></span>
                </td>
            </tr>
            <tr class="shipping">
                <th colspan="4" class="mark" scope="row">
                    <?= __('VAT') ?>
                </th>
                <td class="amount" data-th="VAT &amp; VAT">
                    <span class="price"><?= $block->safeGet($order, 'Currency Code') ?> <?= number_format((float)$block->safeGet($order, 'Amount Including VAT') - (float)$block->safeGet($order, 'Amount'), 2, ',', '.') ?></span>
                </td>
            </tr>
            <tr class="grand_total">
                <th colspan="4" class="mark" scope="row">
                    <strong><?= __('Grand Total') ?></strong>
                </th>
                <td class="amount" data-th="Grand Total">
                    <strong><span class="price"><?= $block->safeGet($order, 'Currency Code') ?> <?= number_format((float)$block->safeGet($order, 'Amount Including VAT'), 2, ',', '.') ?></span></strong>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>

    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="/orders/orderlist/">
                <span><?= __('Back to My Quotes') ?></span>
            </a>
        </div>
    </div>
</div>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= __('Quote Information') ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-order-shipping-address">
            <strong class="box-title"><span><?= __('Shipping Address') ?></span></strong>
            <div class="box-content">
                <address><?= $block->safeGet($order, 'Ship-to Name') ?><br/>
                    <?= $block->safeGet($order, 'Ship-to Address') ?><br />
                    <?= $block->safeGet($order, 'Ship-to City') ?>,  <?= $block->safeGet($order, 'Ship-to Post Code') ?><br/>
                    <?= $block->safeGet($order, 'Ship-to Country/Region Code') ?><br/>
                </address>
            </div>
        </div>
        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span><?= __('Shipping Method') ?></span>
            </strong>
            <div class="box-content">
                <div><?= $block->safeGet($order, 'Shipment Method Code') ?></div>
            </div>
        </div>
        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= __('Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address><?= $block->safeGet($order, 'Bill-to Name') ?><br/>
                    <?= $block->safeGet($order, 'Bill-to Address') ?><br />
                    <?= $block->safeGet($order, 'Bill-to City') ?>,  <?= $block->safeGet($order, 'Bill-to Post Code') ?><br/>
                    <?= $block->safeGet($order, 'Bill-to Country/Region Code') ?><br/>
                </address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= __('Payment Method') ?></span>
            </strong>
            <div class="box-content">
                <dl class="payment-method checkmemo">
                    <?= $block->safeGet($order, 'Payment Method Code') ?>
                </dl>
            </div>
        </div>
    </div>
</div>
