<?php
/** @var \Commerce365\Quotes\Block\QuoteList $block */
$totalResults = 0;
$orders = [];

$ordersResponse = $this->getQuotes();
if (!empty($ordersResponse)) {
    $orders = $ordersResponse["salesDocuments"];
    $totalResults = $ordersResponse["totalResults"];
}

?>

<div class="table-wrapper orders-history">
<?php if (count($orders) > 0): ?>
    <form action="<?= $this->getFilterActionUrl() ?>" method="get">
        <div class="search-form-fields">
            <input type="text" placeholder="<?= __('Search...') ?>" name="searchString"/>
            <button type="submit" title="<?= __('Search') ?>" class="action primary">
                <span><?= __('Search') ?></span>
            </button>
        </div>
    </form>
    <?php if ($this->getSearchString()): ?>
        <?= __('Current filter')?>: <?= $this->getSearchString()?>
        <a href="<?= $this->getFilterActionUrl()?>"><?= __('Reset') ?></a>
    <?php endif; ?>
    <table class="data table table-order-items history" id="my-orders-table">
        <thead>
        <tr>
            <th scope="col" class="col id">
                <a href="<?= $this->getSortLink('No.')?>">
                    <?= __('Quote #') ?>
                    <?= $this->getSortIcon('No.') ?>
                </a>
            </th>
            <th scope="col" class="col id">
                <a href="<?= $this->getSortLink('Status')?>">
                    <?= __('Status') ?>
                    <?= $this->getSortIcon('Status') ?>
                </a>
            </th>
            <th scope="col" class="col date">
                <a href="<?= $this->getSortLink('Document Date')?>">
                    <?= __('Date') ?>
                    <?= $this->getSortIcon('Document Date') ?>
                </a>
            </th>
            <th scope="col" class="col shipping">
                <a href="<?= $this->getSortLink('Ship-to Name')?>">
                    <?= __('Bill To') ?>
                    <?= $this->getSortIcon('Ship-to Name') ?>
                </a>
            </th>
            <th scope="col" class="col total">
                <a href="<?= $this->getSortLink('Amount Including VAT')?>">
                    <?= __('Quote Total') ?>
                    <?= $this->getSortIcon('Amount Including VAT') ?>
                </a>
            </th>
            <th scope="col" class="col actions">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($orders as $order): ?>
            <tr>
                <td data-th="Order #" class="col id"><?= $order["No."] ?></td>
                <td data-th="Status" class="col status"><?= $block->getQuoteStatus($order) ?></td>
                <td data-th="Date" class="col date"><?= date_format(date_create($order["Document Date"]), "d-m-Y") ?></td>
                <td data-th="Ship To #" class="col id"><?= $order["Ship-to Name"] ?></td>
                <td data-th="Total" class="col total"><?= $order["Currency Code"] ?> <?= number_format((float)$order["Amount Including VAT"], 2, ',', '.') ?></td>
                <td data-th="Actions" class="col actions">
                    <a href="<?= $this->getViewUrl($order["id"]); ?>" class="action view">
                        <span><?= __("View Quote") ?></span>
                    </a>
                    <a href="<?= $order["PDFUrl"] ?>" class="action order" target="_blank">
                        <span>PDF</span>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="message info empty"><span><?= __('No quotes found.') ?></span></div>
<?php endif; ?>
</div>

<?php if ($totalResults > $block->getPageSize()): ?>
    <div>
       <?= __('Page:') ?> <?= $block->getPage() ?> <?= __('of') ?> <?= $ordersResponse["totalPages"] ?>
    </div>
    <div>
        <?php if ($block->getPage() > 1): ?>
        <a href="<?= $this->getPreviousPageUrl($block->getPage()) ?>" class="action order"><?= __('Previous') ?></a>
        <?php endif; ?>
        <?php if ($block->getPage() > 1 && $block->getPage() < $ordersResponse["totalPages"]): ?>
            -
        <?php endif; ?>
        <?php if ($block->getPage() < $ordersResponse["totalPages"]): ?>
        <a href="<?= $this->getNextPageUrl($block->getPage()) ?>" class="action order"><?= __('Next') ?></a>
        <?php endif; ?>
    </div>
<?php endif; ?>

<!--

Below is a list of all sales quote header fields
All these fields are available in the API response, as well as any custom field added by customer/partner/other ISV

[DocumentType]
[No]
[SelltoCustomerNo]
[BilltoCustomerNo]
[BilltoName]
[BilltoName2]
[BilltoAddress]
[BilltoAddress2]
[BilltoCity]
[BilltoContact]
[YourReference]
[ShiptoCode]
[ShiptoName]
[ShiptoName2]
[ShiptoAddress]
[ShiptoAddress2]
[ShiptoCity]
[ShiptoContact]
[OrderDate]
[PostingDate]
[ShipmentDate]
[PaymentTermsCode]
[DueDate]
[ShipmentMethodCode]
[LocationCode]
[ShortcutDimension1Code]
[ShortcutDimension2Code]
[LanguageCode]
[SalespersonCode]
[Amount]
[AmountIncludingVAT]
[CombineShipments]
[VATCountryRegionCode]
[SelltoCustomerName]
[SelltoCustomerName2]
[SelltoAddress]
[SelltoAddress2]
[SelltoCity]
[SelltoContact]
[BilltoPostCode]
[BilltoCounty]
[BilltoCountryRegionCode]
[SelltoPostCode]
[SelltoCounty]
[SelltoCountryRegionCode]
[ShiptoPostCode]
[ShiptoCounty]
[ShiptoCountryRegionCode]
[DocumentDate]
[ExternalDocumentNo]
[PaymentMethodCode]
[ShippingAgentCode]
[PackageTrackingNo]
[Status]
[PrepaymentPercentage]
[PrepaymentDueDate]
[QuoteNo]
[SelltoContactNo]
[BilltoContactNo]
[ShippedNotInvoiced]
[CompletelyShipped]
[Shipped]
[RequestedDeliveryDate]
[PromisedDeliveryDate]
[ShippingAgentServiceCode]
[NoOfLines]
[WebOrder]
[WebOrderId]
[PdfFileName]
[PdfUrl]
[CurrencyCode]
[Currency]
[ShipmentMethod]
[PaymentTerms]
[PaymentMethod]

-->

<!--

Below is a list of all sales quote line fields

[DocumentType]
[SelltoCustomerNo]
[DocumentNo]
[LineNo]
[Type]
[No]
[NoIntegrationId]
[LocationCode]
[PostingGroup]
[ShipmentDate]
[Description]
[Description2]
[UnitofMeasure]
[Quantity]
[OutstandingQuantity]
[QtytoInvoice]
[QtytoShip]
[UnitPrice]
[VATPercentage]
[LineDiscountPercentage]
[LineDiscountAmount]
[Amount]
[AmountIncludingVAT]
[GrossWeight]
[NetWeight]
[UnitsperParcel]
[UnitVolume]
[ShortcutDimension1Code]
[ShortcutDimension2Code]
[CustomerPriceGroup]
[OutstandingAmount]
[QtyShippedNotInvoiced]
[ShippedNotInvoiced]
[QuantityShipped]
[QuantityInvoiced]
[ShipmentNo]
[ShipmentLineNo]
[BilltoCustomerNo]
[InvDiscountAmount]
[DropShipment]
[CurrencyCode]
[ReservedQuantity]
[VATBaseAmount]
[LineAmount]
[PrepaymentPercentage]
[PostingDate]
[VariantCode]
[WebOrder]
[WebOrderId]
[IsShippingCostLine]
[Currency]
[CrossReferenceNo]

-->
