<?php declare(strict_types=1);

use Commerce365\Quotes\Block\QuoteDetails;
use Magento\Framework\Escaper;

/** @var QuoteDetails  $block */
/** @var Escaper $escaper */

$order = $block->getQuote();
$orderLines = $order["Lines"];
?>

<div class="md:flex md:justify-between items-center mb-3">
    <div class="lg:flex items-center text-center md:text-left">
        <div class="lg:inline-block">
            <h2 class="text-2xl">
                <span><?= $escaper->escapeHtml(__('Quote # %1', $order["No."])) ?></span>
            </h2>
            <div class="order-date">
                <span class="label"><?= $escaper->escapeHtml(__('Quote Date:')) ?></span>
                <date><?php echo date_format(date_create($order["Document Date"]), "d-m-Y") ?></date>
            </div>
        </div>
        <div class="mt-3 md:mt-0 lg:inline-block lg:ml-5">
            <span
                class="order-status inline-block px-3 py-3 border rounded border-container"><?= $block->getQuoteStatus($order) ?></span>
        </div>
    </div>
    <div class="actions">
        <a href="<?= $order["PDFUrl"] ?>" class="btn btn-secondary mb-4 order" style="justify-content: center;"
            target="_blank">
            <?= $escaper-> escapeUrl(__('Download PDF')) ?>
        </a>
    </div>
</div>

<div class="order-details-items ordered">
    <div class="-mx-4">
        <ul class="items order-links">
            <li class="nav item current">
                <strong><?= $escaper->escapeHtml(__('Items Quoted')) ?></strong>
            </li>
        </ul>
    </div>
    <div class="p4 card">
        <table id="my-orders-table" class="w-full">
            <caption class="order-title sr-only"><?= $escaper->escapeHtml(__('Items Quoted')) ?></caption>
            <thead>
                <tr>
                    <th class="col name p-2 text-left"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                    <th class="col sku p-2 text-left"><?= $escaper->escapeHtml(__('SKU')) ?></th>
                    <th class="col price p-2 text-left"><?= $escaper->escapeHtml(__('Price')) ?></th>
                    <th class="col qty p-2 text-left"><?= $escaper->escapeHtml(__('Qty')) ?></th>
                    <th class="col subtotal p-2 text-left"><?= $escaper->escapeHtml(__('Subtotal')) ?></th>
                </tr>
            </thead>

            <?php foreach ($orderLines as $orderLine): ?>
            <?php
                $itemNo = '';
                if ((int)$orderLine["Type"] > 0) {$itemNo = $orderLine["No."];}
            ?>
            <tbody>
                <?php if ($orderLine["Type"] < 1): ?>
                <tr id="order-item-row-1">
                    <td class="col name p-2" data-th="Product Name">
                        <strong class="product name product-item-name"><?= $orderLine["Description"] ?>'</strong>
                    </td>
                    <td class="col sku p-2" data-th="SKU"></td>
                    <td class="col price p-2" data-th="Price">
                    </td>
                    <td class="col qty p-2" data-th="Qty">
                    </td>
                    <td class="col subtotal p-2" data-th="Subtotal">
                    </td>
                </tr>
                <?php else: ?>
                <tr id="order-item-row-1">
                    <td class="col name p-2" data-th="Product Name">
                        <strong class="product name product-item-name"><?= $orderLine["Description"] ?></strong>
                    </td>
                    <td class="col sku p-2" data-th="SKU"><?= $itemNo ?></td>
                    <td class="col price p-2" data-th="Price">
                        <span class="price-excluding-tax" data-label="Excl. Tax">
                            <span class="cart-price">
                                <span
                                    class="price"><?= $orderLine["Currency Code"] ?><?= number_format((float)$orderLine["Amount"] / (float)$orderLine["Quantity"], 2, ',', '.') ?></span>
                            </span>
                        </span>
                    </td>
                    <td class="col qty p-2" data-th="Qty">
                        <ul class="items-qty">
                            <li class="item">
                                <span class="content"><?= $orderLine["Quantity"] ?></span>
                            </li>
                        </ul>
                    </td>
                    <td class="col subtotal p-2" data-th="Subtotal">
                        <span class="price-excluding-tax" data-label="Excl. Tax">
                            <span class="cart-price">
                                <span
                                    class="price"><?= $orderLine["Currency Code"] ?><?= number_format((float)$orderLine["Line Amount"], 2, ',', '.') ?></span>
                            </span>
                        </span>
                    </td>
                </tr>
                <?php endif; ?>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr class="subtotal">
                    <th colspan="4" class="p-2 text-right" scope="row">
                        <?= $escaper->escapeHtml(__('Subtotal')) ?>
                    </th>
                    <td class="amount p-2" data-th="Subtotal">
                        <span class="price"><?= $order["Currency Code"]; ?>
                            <?= number_format((float)$order["Amount"], 2, ',', '.') ?></span>
                    </td>
                </tr>
                <tr class="shipping">
                    <th colspan="4" class="p-2 text-right" scope="row">
                        <?= $escaper->escapeHtml(__('VAT')) ?>
                    </th>
                    <td class="amount p-2" data-th="VAT &amp; VAT">
                        <span class="price"><?= $order["Currency Code"]; ?>
                            <?= number_format((float)$order["Amount Including VAT"] - (float)$order["Amount"], 2, ',', '.') ?></span>
                    </td>
                </tr>
                <tr class="grand_total">
                    <th colspan="4" class="p-2 text-right" scope="row">
                        <strong><?= $escaper->escapeHtml(__('Grand Total')) ?></strong>
                    </th>
                    <td class="amount p-2" data-th="Grand Total">
                        <strong><span class="price"><?= $order["Currency Code"]; ?>
                                <?= number_format((float)$order["Amount Including VAT"], 2, ',', '.') ?></span></strong>
                    </td>
                </tr>
            </tfoot>
        </table>
        <div class="actions-toolbar">
            <div class="secondary">
                <a class="action back" href="/orders/orderlist/">
                    <span><?= $escaper->escapeHtml(__('Back to My Quotes')) ?></span>
                </a>
            </div>
        </div>
    </div>


</div>
<div class="mt-8">
    <div class="block-title mb-2">
        <strong><?= $escaper->escapeHtml(__('Quote Information')) ?></strong>
    </div>
    <div class="p-4 card">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="order-shipping-address">
                <strong class="block text-lg mb-2"><?= $escaper->escapeHtml(__('Shipping Address')) ?></strong>
                <div class="box-content">
                    <address class="not-italic"><?= $order["Ship-to Name"]; ?><br />
                        <?= $order["Ship-to Address"]; ?><br />
                        <?= $order["Ship-to City"]; ?>, <?= $order["Ship-to Post Code"]; ?><br />
                        <?= $order["Ship-to Country/Region Code"]; ?><br />
                    </address>
                </div>
            </div>
            <div class="order-shipping-method">
                <strong class="block text-lg mb-2"><?= $escaper->escapeHtml(__('Shipping Method')) ?></strong>
                <div class="box-content">
                    <div><?= $order["Shipment Method Code"]; ?></div>
                </div>
            </div>
            <div class="order-billing-address">
                <strong class="block text-lg mb-2"><?= $escaper->escapeHtml(__('Billing Address')) ?></strong>
                <div class="box-content">
                    <address class="not-italic"><?= $order["Bill-to Name"]; ?><br />
                        <?= $order["Bill-to Address"]; ?><br />
                        <?= $order["Bill-to City"]; ?>, <?= $order["Bill-to Post Code"]; ?><br />
                        <?= $order["Bill-to Country/Region Code"]; ?><br />
                    </address>
                </div>
            </div>
            <div class="box box-order-billing-method">
                <strong class="block text-lg mb-2"><?= $escaper->escapeHtml(__('Payment Method')) ?></strong>
                <div class="box-content">
                    <dl class="payment-method checkmemo">
                        <?php echo $order["Payment Method Code"]; ?>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>